### ISSUE TITLE
C compiler

### ISSUE THREAD

**Issue by deleterium** [ciyam/AT#4]
Hello!

A long time ago this assembler language was adopted by burstcoin (now signum). A few months ago I started a C compiler and currently it is stable. The compiler is written in Typescript and runs in the browser. If you are interested in know more, check https://github.com/deleterium/SmartC

I also made an assembler interpreter to simulate the blockchain operation, so it is possible to simulate any assembly program (with some simplifications, of course). I called it SC-Simulator and can be found at https://github.com/deleterium/SC-Simulator

And there is also a dissassembler, optimizer and recompiler for assembly programs: https://github.com/deleterium/Signum-D-Or

Thanks for all work done for burstcoin/signum!

**Comment by ciyam** [comment]
Well done! Very impressive work and the simulator is a great addition.

Great to see that AT is still alive and executing smart contracts after all these years. :)
